In [1]:
import numpy as np
import pandas as pd

# DAY 9
## 과제 1

In [2]:
arr = np.arange(20).reshape(5, 4)
axis_ABC = np.array(['A', 'A', 'B', 'C', 'C'])

In [3]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
axis_ABC

array(['A', 'A', 'B', 'C', 'C'], dtype='<U1')

https://rfriend.tistory.com/291?category=675917

In [5]:
arr[axis_ABC == 'A', :]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr[axis_ABC == 'A',:2]

array([[0, 1],
       [4, 5]])

In [8]:
arr[axis_ABC != 'A',]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
arr[(axis_ABC != 'A') & (axis_ABC != 'B')]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
arr = np.arange(20).reshape(5, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
arr[(axis_ABC == 'A')] = 0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arr[(arr >= 8) & (arr <= 15)] = 10

arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [16, 17, 18, 19]])

## 과제 2

Fancy Indexing 이란 무엇인가요?
+ 정수 배열을 인덱서로 사용해서 다채원 배열로 부터 인덱싱 하는 방법

In [24]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
a[[1,2]]

array([[3, 4, 5],
       [6, 7, 8]])

In [26]:
a[[-1, -2]]

array([[12, 13, 14],
       [ 9, 10, 11]])

In [27]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [30]:
a[[0, 2, 4]][:, [0, 2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14]])

In [33]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
a_copy = a[[0, 2, 4]][:, [0, 2]]
a_copy[0, :] = 100
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [34]:
# 원본 배열에 아무런 영향이 없다. 기존의 인덱싱 &슬라이싱에서는 copy가 아니라 뷰를 생성..

In [35]:
a_copy

array([[100, 100],
       [  6,   8],
       [ 12,  14]])

## 과제 3

In [36]:
a = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])
a

array([-4.62, -2.19,  0.  ,  1.57,  3.4 ,  4.06])

In [44]:
# 0.5 를 기준으로 올림 또는 내림
print(np.around(a))
# 소수점 첫 번째 자리수까지 반올림
print(np.round_(a,1))
# 가장 가까운 정수로 올림 혹은 내림
print(np.rint(a))
# '0' 방향으로 가장 가까운 정수로 올림 혹은 내림
print(np.fix(a))
# 각 원소 값보다 크거나 같은 가장 작은 정수 값으로 올림
print(np.ceil(a))
# 각 원소 값보다 작거나 같은 가장 큰 정수 값 (바닥 값)으로 내림
print(np.floor(a))
# 각 원소의 소수점 부분은 잘라버리고 정수값만 남김
print(np.trunc(a))

[-5. -2.  0.  2.  3.  4.]
[-4.6 -2.2  0.   1.6  3.4  4.1]
[-5. -2.  0.  2.  3.  4.]
[-4. -2.  0.  1.  3.  4.]
[-4. -2.  0.  2.  4.  5.]
[-5. -3.  0.  1.  3.  4.]
[-4. -2.  0.  1.  3.  4.]


## 과제 4

In [45]:
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2], [3, 4]])

print(b)
print(c)

[1 2 3 4]
[[1 2]
 [3 4]]


In [46]:
#배열 원소 간 곱 범영 함수!!!
np.prod(b)

24

In [47]:
np.prod(c)

24

In [48]:
np.prod(c, axis=0)

array([3, 8])

In [49]:
np.prod(c, axis=1)

array([ 2, 12])

In [50]:
np.sum(b)

10

In [51]:
np.sum(b, keepdims=True)

array([10])

In [52]:
d = np.array([[1, 2], [3, np.nan]])
d

array([[ 1.,  2.],
       [ 3., nan]])

In [53]:
np.nanprod(d, axis =0)

array([3., 2.])

In [54]:
np.nanprod(d, axis =1)

array([2., 3.])

In [55]:
np.nansum(d, axis=1)

array([3., 3.])

In [56]:
e = np.array([1, 2, 3, 4])
f = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print(f)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [57]:
# 배열 원소 간 누적 곱하기 범용 함수
np.cumprod(e)

array([ 1,  2,  6, 24], dtype=int32)

In [59]:
np.cumprod(f, axis =0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [60]:
np.cumprod(f, axis =1)

array([[  1,   2,   6],
       [  4,  20, 120]], dtype=int32)

In [61]:
np.cumsum(f, axis =1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [62]:
g = np.array([1, 2, 4, 10, 13, 20])
g

array([ 1,  2,  4, 10, 13, 20])

In [63]:
np.diff(g)

array([1, 2, 6, 3, 7])

In [64]:
np.diff(g, n=2)

array([ 1,  4, -3,  4])

In [65]:
h = np.array([[ 1,  2,  4,  8],
             [10, 13, 20, 15]])
h

array([[ 1,  2,  4,  8],
       [10, 13, 20, 15]])

In [66]:
np.ediff1d(h)
# 차분한 결과를 1차원 배열로 반환해주는 함수

array([ 1,  2,  4,  2,  3,  7, -5])

## 과제 5

In [67]:
x = np.array([0.00001, 1, 2, 4, 10, 100])

In [68]:
np.exp(x)

array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 5.45981500e+01,
       2.20264658e+04, 2.68811714e+43])

In [69]:
np.log(x)

array([-11.51292546,   0.        ,   0.69314718,   1.38629436,
         2.30258509,   4.60517019])

In [70]:
np.log10(x)

array([-5.        ,  0.        ,  0.30103   ,  0.60205999,  1.        ,
        2.        ])

In [71]:
np.log2(x)

array([-16.60964047,   0.        ,   1.        ,   2.        ,
         3.32192809,   6.64385619])

In [72]:
np.log(x+1)

array([9.99995000e-06, 6.93147181e-01, 1.09861229e+00, 1.60943791e+00,
       2.39789527e+00, 4.61512052e+00])