## DAY 7

In [1]:
import numpy as np
x = np.arange(12).reshape(3, 4)

### 과제 1

In [2]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
np.ravel(x, order = 'F')
#Fortran과 같은 순서로 인덱싱하여 평평하게 배열

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [8]:
y = np.arange(12).reshape(2, 3, 2)
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [9]:
np.ravel(y)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 과제 2

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

In [15]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.column_stack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([[6, 7, 8], [9, 10, 11]])

In [22]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
np.concatenate((c.T, d.T), axis=1)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

### 과제 3

In [27]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 6, 5])

In [28]:
#교집합 정렬 반환
np.intersect1d(x, y)

array([3, 4])

In [29]:
#합집합을 정려하여 반환
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6])

In [30]:
# 첫번째 배열이 두번째 배열의 원소를 포함하고 있는지의 여부의 불리언 배열을 반환
np.in1d(x,y)


array([False, False,  True,  True])

In [32]:
#첫번째 배열 x로부터 두번째 배열 y를 뺀 차집합을 반환
np.setdiff1d(x,y)

array([1, 2])

In [31]:
#두 배열 x,y 합집합에서 교집합을 뺀 대칭차집합을 반환
np.setxor1d(x,y)

array([1, 2, 5, 6])

### 과제 4


In [33]:
x = np.array([5, 4, 3, 2, 1, 0])

In [34]:
np.min(x)

0

In [35]:
np.max(x)

5

In [37]:
x.min()

0

In [38]:
x.max()

5

In [39]:
np.argmax(x)

0

In [40]:
np.argmin(x)

5

In [42]:
np.where(x>=3, 3, x)

array([3, 3, 3, 2, 1, 0])

### 과제 5

In [43]:
x = np.array([4, 2, 6, 5, 1, 3, 0])

In [44]:
np.sort(x)

array([0, 1, 2, 3, 4, 5, 6])

In [46]:
x.sort()
x

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
np.sort(x)[::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [48]:
x[np.argsort(-x)]

array([6, 5, 4, 3, 2, 1, 0])

In [49]:
x2 = np.array([[2, 1, 6],
               [0, 7, 4],
               [5, 3, 2]])

In [50]:
np.sort(x2, axis=1)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])