# DAY 5
## 과제 1

+ 다음의 train DataFrame data 를 0 ~ 1 범위로 변환하는 scaler를 만들어보세요
+ 해당 scaler 로 train Data 를 변환한 결과를 출력해보세요
+  test DataFrame data 를 해당 scaler 로 변환해 보세요


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

train = np.array([[10., -10., 1.],
                  [5., 0., 2.],
                  [0., 10., 3.]])

test = np.array([[9., -10., 1.],
                 [5., -5., 3.],
                 [1., 0., 5.]])

In [12]:
MinMaxScaler().fit_transform(train.reshape(-1,1))

array([[1.  ],
       [0.  ],
       [0.55],
       [0.75],
       [0.5 ],
       [0.6 ],
       [0.5 ],
       [1.  ],
       [0.65]])

In [13]:
MinMaxScaler().fit_transform(test.reshape(-1,1))

array([[1.        ],
       [0.        ],
       [0.57894737],
       [0.78947368],
       [0.26315789],
       [0.68421053],
       [0.57894737],
       [0.52631579],
       [0.78947368]])

## 과제 2
- 다음 X의 데이터를 이항변수화 변환을 수행해보세요
- 이 때, 기준값(threshold) 은 2.0 으로 설정하여 이항변수화를 변환해보세요

In [14]:
X = np.array([[ 10., -10., 1.],
              [ 5., 0., 2.],
              [ 0., 10., 3.]])

In [16]:
X

array([[ 10., -10.,   1.],
       [  5.,   0.,   2.],
       [  0.,  10.,   3.]])

In [18]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=2.0).fit(X)
binarizer.transform(X)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 1.]])

## 과제 3
- 다음의 train 데이터(범주형) 를 이항변수화(One-Hot encoding) 해보세요
- 이 때, 다음의 제약조건을 충족하여야 합니다.
- train data 에 포함되어있지 않은 category 가 발생할 경우, 무시

In [19]:
data_train = np.array([[0, 0, 0],
                       [0, 1, 1],
                       [0, 2, 2],
                       [1, 0, 3],
                       [1, 1, 4]])

In [35]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
enc.fit(data_train)
enc.transform(data_train).toarray()

array([[1., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 1.]])

## 과제 4
+ 다음의 데이터를 활용하여 연속형 변수 C1 을 이산형화 시켜보세요
+ C1 컬럼의 데이터를 10개의 구간으로 나누고, 이를 (1 ~ 10) 까지로 만들어본 후, C1_bin 컬럼에 넣어 보세요.
+ 만든 C1_bin 컬럼 값을 다시 one-hot encoding 을 수행해보세요
+ 이 때, 첫 번째 변수를 삭제해보세요

In [38]:
np.random.seed(10)
df = pd.DataFrame({'C1': np.random.randn(20),
                   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
                          'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})

In [39]:
df

C1 C2
0   1.331587  a
1   0.715279  a
2  -1.545400  a
3  -0.008384  a
4   0.621336  a
5  -0.720086  a
6   0.265512  a
7   0.108549  a
8   0.004291  a
9  -0.174600  a
10  0.433026  b
11  1.203037  b
12 -0.965066  b
13  1.028274  b
14  0.228630  b
15  0.445138  b
16 -1.136602  b
17  0.135137  b
18  1.484537  b
19 -1.079805  b

  (1) np.digitize(data, bins)를 이용한 연속형 변수의 이산형화 (discretization)

출처: https://rfriend.tistory.com/273?category=675917 [R, Python 분석과 프로그래밍의 친구 (by R Friend)]

In [40]:
bins = np.linspace(df.C1.min(), df.C1.max(), 10)

In [41]:
bins

array([-1.54540029, -1.20874059, -0.87208089, -0.53542119, -0.19876149,
        0.1378982 ,  0.4745579 ,  0.8112176 ,  1.1478773 ,  1.484537  ])

In [42]:
df['C1_bin'] = np.digitize(df['C1'], bins)
df

C1 C2  C1_bin
0   1.331587  a       9
1   0.715279  a       7
2  -1.545400  a       1
3  -0.008384  a       5
4   0.621336  a       7
5  -0.720086  a       3
6   0.265512  a       6
7   0.108549  a       5
8   0.004291  a       5
9  -0.174600  a       5
10  0.433026  b       6
11  1.203037  b       9
12 -0.965066  b       2
13  1.028274  b       8
14  0.228630  b       6
15  0.445138  b       6
16 -1.136602  b       2
17  0.135137  b       5
18  1.484537  b      10
19 -1.079805  b       2

In [45]:
pd.get_dummies(df['C1_bin'], drop_first= True)

2   3   5   6   7   8   9   10
0    0   0   0   0   0   0   1   0
1    0   0   0   0   1   0   0   0
2    0   0   0   0   0   0   0   0
3    0   0   1   0   0   0   0   0
4    0   0   0   0   1   0   0   0
5    0   1   0   0   0   0   0   0
6    0   0   0   1   0   0   0   0
7    0   0   1   0   0   0   0   0
8    0   0   1   0   0   0   0   0
9    0   0   1   0   0   0   0   0
10   0   0   0   1   0   0   0   0
11   0   0   0   0   0   0   1   0
12   1   0   0   0   0   0   0   0
13   0   0   0   0   0   1   0   0
14   0   0   0   1   0   0   0   0
15   0   0   0   1   0   0   0   0
16   1   0   0   0   0   0   0   0
17   0   0   1   0   0   0   0   0
18   0   0   0   0   0   0   0   1
19   1   0   0   0   0   0   0   0

+ 다음의 데이터를 활용하여 연속형 변수 C1을 이산형화 시켜보세요
- C1 컬럼의 데이터의 1분위수(Q1), 3분위수(Q3)를 계산해보세요
- 계산된 Q1, Q3 값을 토대로 4개의 구간을 해당 값 --> (quarter01, quarter02, quarter03, quarter04) 으로 나누고 quarter 컬럼에 할당해보세요

In [50]:
np.random.seed(10)
df = pd.DataFrame({'C1': np.random.randn(20),
                   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
                          'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})

In [47]:
df

C1 C2
0   1.331587  a
1   0.715279  a
2  -1.545400  a
3  -0.008384  a
4   0.621336  a
5  -0.720086  a
6   0.265512  a
7   0.108549  a
8   0.004291  a
9  -0.174600  a
10  0.433026  b
11  1.203037  b
12 -0.965066  b
13  1.028274  b
14  0.228630  b
15  0.445138  b
16 -1.136602  b
17  0.135137  b
18  1.484537  b
19 -1.079805  b

In [56]:
Q1 = np.percentile(df['C1'], 25)
Q2 = np.percentile(df['C1'], 50)
Q3 = np.percentile(df['C1'], 75)

df['quarter'] = np.where(df['C1'] >= Q3, 'quarter01', np.where(df['C1'] >= Q1, 'quarter02',
                                                               np.where(df['C1']== Q2, 'quarter03', 'quarter04')))

In [57]:
df

C1 C2    quarter
0   1.331587  a  quarter01
1   0.715279  a  quarter01
2  -1.545400  a  quarter04
3  -0.008384  a  quarter02
4   0.621336  a  quarter02
5  -0.720086  a  quarter04
6   0.265512  a  quarter02
7   0.108549  a  quarter02
8   0.004291  a  quarter02
9  -0.174600  a  quarter02
10  0.433026  b  quarter02
11  1.203037  b  quarter01
12 -0.965066  b  quarter04
13  1.028274  b  quarter01
14  0.228630  b  quarter02
15  0.445138  b  quarter02
16 -1.136602  b  quarter04
17  0.135137  b  quarter02
18  1.484537  b  quarter01
19 -1.079805  b  quarter04

## 과제 5
다음의 데이터를 아래와 같이 변환해보세요
x1, x2 컬럼 데이터를 가지고, 다항 2차수(1, x1, x2, x1^2, x1*x2, x2^2) 컬럼을 만들어보세요

In [59]:
X = np.arange(6).reshape(3, 2)

In [105]:
np.hstack([X[:, 0].reshape(-1,1)**0  ,X[:, 0].reshape(-1,1), X[:, 1].reshape(-1,1), 
         X[:, 0].reshape(-1,1) *  X[:, 0].reshape(-1,1), 
          X[:, 0].reshape(-1,1) * X[:, 1].reshape(-1,1),
          X[:, 1].reshape(-1,1) * X[:, 1].reshape(-1,1)
     ])

array([[ 1,  0,  1,  0,  0,  1],
       [ 1,  2,  3,  4,  6,  9],
       [ 1,  4,  5, 16, 20, 25]])

In [90]:
X[:, 0].reshape(-1,1).shape

(3, 1)

sklearn.preprocessing.PolynomialFeatures()

출처: https://rfriend.tistory.com/274?category=675917 [R, Python 분석과 프로그래밍의 친구 (by R Friend)]
방법도 있음..

In [106]:
X2 = np.arange(9).reshape(3, 3)

In [107]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
poly.fit_transform(X2)

array([[ 1.,  0.,  1.,  2.,  0.,  0.,  0.,  1.,  2.,  4.],
       [ 1.,  3.,  4.,  5.,  9., 12., 15., 16., 20., 25.],
       [ 1.,  6.,  7.,  8., 36., 42., 48., 49., 56., 64.]])