# DAY 8
## 과제 1

In [1]:
import numpy as np
import pandas as pd

In [15]:
x = np.array([1, 1, 2, 2])
y = np.array([1, 2, 3, 4])

In [13]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 1)
# Out[6]: array([ 2., 3., 4., 5.])
x+y

array([2, 3, 5, 6])

In [17]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 2)
# Out[10]: array([ 0., 1., 1., 2.])
abs(x-y)

array([0, 1, 1, 2])

In [20]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 4)
# Out[13]: array([ 1., 1., 8., 16.])
x**y


array([ 1,  1,  8, 16], dtype=int32)

In [21]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 5)
# Out[25]: array([ 1., 2., 6., 8.])

x*y

array([1, 2, 6, 8])

In [22]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 6)
# Out[26]: array([ 1. , 2. , 1.5, 2. ])

y/x

array([1. , 2. , 1.5, 2. ])

In [28]:
# 다음의 결과를 도출해보세요. 이 때 Vectorization 연산으로 결과를 도출해보세요(-- 7)
# Out[29]: array([ 1., 2., 9., 16.])
y ** x

array([ 1,  2,  9, 16], dtype=int32)

In [35]:
x = np.array([1, 1, 2, 2])
y = np.array([1, 2, 3, 4])

In [26]:
# 배열간 비교 연산을 통해, =, !=, >=, >, <=, < 6가지 케이스를 비교해서 boolean 형태로 출력해보세요
# 다음과 같은 결과값이 도출되어야 합니다.

"""
Out[32]: array([ True, False, False, False], dtype=bool)
Out[33]: array([False, True, True, True], dtype=bool)
Out[34]: array([False, False, False, False], dtype=bool)
Out[35]: array([ True, False, False, False], dtype=bool)
Out[36]: array([False, True, True, True], dtype=bool)
Out[37]: array([ True, True, True, True], dtype=bool)
"""

'\nOut[32]: array([ True, False, False, False], dtype=bool)\nOut[33]: array([False, True, True, True], dtype=bool)\nOut[34]: array([False, False, False, False], dtype=bool)\nOut[35]: array([ True, False, False, False], dtype=bool)\nOut[36]: array([False, True, True, True], dtype=bool)\nOut[37]: array([ True, True, True, True], dtype=bool)\n'

In [42]:
print(x==y)
print(x!=y)
print(x>y)
print(x>=y)
print(x<y)
print(x<=y)

[ True False False False]
[False  True  True  True]
[False False False False]
[ True False False False]
[False  True  True  True]
[ True  True  True  True]


In [47]:
x = np.array([1, 1, 2, 2])
y = np.array([1, 2, 3, 4])

z = y.copy()

# np.array_equal(x, y) # -- (1) ? 
# np.array_euqal(y, z) # -- (2) ?

print(np.array_equal(x, y))
print(np.array_equal(y, z))

False
True


In [54]:
x4 = np.array([1, 1, 0, 0])
x5 = np.array([1, 0, 1, 0])

print("x4: ", x4)
print("x5: ", x5)

x4:  [1 1 0 0]
x5:  [1 0 1 0]


In [55]:
print(np.logical_and(x4, x5))
print(np.logical_or(x4, x5))
print(np.logical_xor(x4, x5))

[ True False False False]
[ True  True  True False]
[False  True  True False]


In [57]:
x4 = np.array([1, 1, 2, 2])
x5 = np.arange(5)

print("x4: ", x4)
print("x5: ", x5)

print(x4 + x5) # 에러가 나염 -> 브로드 캐스팅이 필요

x4:  [1 1 2 2]
x5:  [0 1 2 3 4]


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

## 과제 2 

In [59]:
a_df = pd.DataFrame({'x1': [1, 2, 3, 4],
                     'x2': [5, 6, 7, 8]})
a_df

x1  x2
0   1   5
1   2   6
2   3   7
3   4   8

In [60]:
a_df+1

x1  x2
0   2   6
1   3   7
2   4   8
3   5   9

In [68]:
b = np.arange(12).reshape((4, 3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
b[:,1] += 1
b[:,2] += 2 
b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [71]:
b = np.arange(12).reshape((4, 3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
c = np.array([0, 1, 2])
b + c

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [70]:
# 배열의 차원 크기, 모양이 다르다고 해서 Broadcasting 이 아무때나 되는 것은 아닙니다. 
#Broadcasting을 시키려면 기준 축에 있는 원소의 크기(개수)가 서로 같아야지 짝을 맞추어서 확산(broadcasting, propagating)을 할 수 있습니다.

# 출처: https://rfriend.tistory.com/287?category=675917 [R, Python 분석과 프로그래밍의 친구 (by R Friend)]

In [73]:
d = np.array([0, 1, 2, 3])
b + d

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [74]:
f = np.arange(24).reshape((2,4,3))
f

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [80]:
g = np.array([1, 1, 1])
# h = np.array([1, 1, 1])

In [81]:
f+g

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

## 과제 3

In [85]:
a = np.array([1, 2, 3, 4])
a_4_1 = a.reshape(-1,1)
print(a_4_1)

# result
# Out[6]:
# array([[ 1.],
#        [ 2.],
#        [ 3.],
#        [ 4.]])

[[1]
 [2]
 [3]
 [4]]


In [91]:
a_4_1 = a[..., np.newaxis]
a_4_1

array([[1],
       [2],
       [3],
       [4]])

In [89]:
b = np.arange(12).reshape(3, 4)
b_3_4_1 = b.reshape(3,4,1)
print(b_3_4_1)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [93]:
b = np.arange(12).reshape(3, 4)
b_3_4_1 = b[:,:, np.newaxis]
print(b_3_4_1)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [104]:
A = np.array([0, 1, 2, 3])
A_2_8 = np.tile(A,(2,2))
A_2_8

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [105]:
B = np.arange(8).reshape(2, 4)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
B_2_8 = np.tile(B, (2,1))
print(B_2_8)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


## 과제 4

In [108]:
a = np.arange(15).reshape(3, 5)
print(a)
print()
print(a.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [110]:
# 다음 데이터의 shape은 (2, 3, 4) 입니다.
# 이를 (2, 4, 3) 으로 변경한 결과를 최소 2가지 방법 이상으로 도출해보세요
b = np.arange(24).reshape(2, 3, 4)
print(b)
print(b.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [112]:
b.reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [123]:
np.swapaxes(b, 1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

## 과제 5

In [127]:
# 다음의 코드에서 -- 1 과 -- 2 는 같은 결과를 도출하나요?
# 아니면 다른 결과를 도출하나요? 그 이유는 무엇인가요 ?
d = np.arange(20).reshape(4, 5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
print(d[0:3, 1:3]) # -- 1
print()
print(d[0:3][1:3]) # -- 2

[[ 1  2]
 [ 6  7]
 [11 12]]

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# -- 1 
# d행렬의 0,1,2 열의 1,2 열의 선택하는 명령

# -- 2
# d행렬의 0,1,2 행을 가져 온 뒤 1, 2 열만 가져옴 -> working sequencially